CREATE DATABASE EMPLOYEEDB1
ON (
    NAME = EMPLOYEEDB1 ,
    FILENAME = '/Users/harshit/Desktop/HS/SQL_PRACTICE/EMPLOYEEDB1.MDF' ,
    SIZE = 5MB , MAXSIZE = 10MB , FILEGROWTH = 2MB )
LOG ON (
    NAME =  EMPLOYEEDB1LOG ,
   FILENAME =  '/Users/harshit/Desktop/HS/SQL_PRACTICE/SQL_PRACTICE/EMPLOYEEDB1_LOG.LDF' ,
    SIZE = 5MB , MAXSIZE = 10MB , FILEGROWTH = 2MB )
